version: "3.5"

services:
  payment:
    build: .
    environment:
      - PORT=8080
      - SERVICE_NAME=payment
      - ENVIRONMENT=production
      - PAYMENT_URL=${PAYMENT_URL}
      - ORDER_URL=${ORDER_URL}
      - OAUTH2_JWKS_ENDPOINT=${OAUTH2_JWKS_ENDPOINT}

    command: "-payment"
    ports:
      - ${PAYMENT_PORT}:8080
    restart: unless-stopped

  order:
    build: .
    environment:
      - PORT=8080
      - SERVICE_NAME=order
      - ENVIRONMENT=production
      - PAYMENT_URL=${PAYMENT_URL}
      - ORDER_URL=${ORDER_URL}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
      - OAUTH2_SCOPES=${OAUTH2_SCOPES}
      - OAUTH2_TOKEN_URL=${OAUTH2_TOKEN_URL}
    command: "-order"
    ports:
      - ${ORDER_PORT}:8080
    restart: unless-stopped